export const availabilityList = {
  monday: [
    'Francesco Molinari',
    'Davide Colucci',
    'Domenico Pace',
    'Michele Lillo',
    'Michele Sette',
    'Salvatore Defino',
    'Michele Porcu',
    'Dario Spinosa',
    'Filippo Addabbo',
    'Marco De Luca',
    'Nicola Sergio',
    'Matteo Attanasio',
    'Gianluca De Vincenzo',
    'Giuseppe Larato',
    'Francesco Giustino'
  ],
  tuesday: [
    'Francesco Molinari',
    'Davide Colucci',
    'Michele Lillo',
    'Michele Sette',
    'Michele Porcu',
    'Pietro Colonna',
    'Andrea Greco',
    'Andrea Fraccalvieri',
    'Alfredo Sette',
    'Filippo Addabbo',
    'Giuseppe Latrofa',
    'Loris Bevilacqua',
    'Marco De Luca',
    'Nicola Sergio',
    'Gianluca De Vincenzo',
    'Ilenia Taccogna'
  ],
  wednesday: [
    'Francesco Molinari',
    'Davide Colucci',
    'Domenico Pace',
    'Michele Lillo',
    'Michele Sette',
    'Michele Porcu',
    'Davide Silletti',
    'Leonardo Galluzzi',
    'Filippo Addabbo',
    'Marco De Luca',
    'Salvatore Defino',
    'Nicola Sergio',
    'Matteo Attanasio',
    'Gianluca De Vincenzo',
    'Dario Spinosa',
    'Andrea Difonzo',
    'Giuseppe Larato',
    'Francesco Giustino'
  ],
  thursday: [
    'Francesco Molinari',
    'Davide Colucci',
    'Michele Lillo',
    'Michele Sette',
    'Michele Porcu',
    'Pietro Colonna',
    'Davide Silletti',
    'Andrea Greco',
    'Andrea Fraccalvieri',
    'Alfredo Sette',
    'Andrea Gargaro',
    'Amedeo D\'Amelio',
    'Filippo Addabbo',
    'Giuseppe Latrofa',
    'Loris Bevilacqua',
    'Marco De Luca',
    'Nicola Sergio',
    'Gianluca De Vincenzo',
    'Ilenia Taccogna'
  ],
  friday: [
    'Francesco Molinari',
    'Davide Colucci',
    'Michele Lillo',
    'Michele Sette',
    'Michele Porcu',
    'Andrea Gargaro',
    'Dario Spinosa',
    'Filippo Addabbo',
    'Luigi Denora',
    'Marco De Luca',
    'Salvatore Defino',
    'Nicola Sergio',
    'Leonardo Galluzzi',
    'Gianluca De Vincenzo',
    'Andrea Difonzo'
  ]
};
